language: go

go:
  - 1.11.x
  
# Only build on master, stable branches and tag
# The stable branch and tag should be leading with numbers
branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

# installing a fixed version because linter deafults change frequently
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0
  - golangci-lint run

# Tests don't work in project root yet so I override
script: go test ./pkg/transforms
